In [1]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
a = np.array([1,5,7])  # 1D array

print(a)
print(type(a))

[1 5 7]
<class 'numpy.ndarray'>


In [6]:
b = np.array([
    [1,2,3],
    [6,7,8]
])

print(b)

[[1 2 3]
 [6 7 8]]


In [11]:
c = np.array([[[1,2,0],[3,4,1]], [[5,6,4],[7,8,6]]])
print(c)

[[[1 2 0]
  [3 4 1]]

 [[5 6 4]
  [7 8 6]]]


In [12]:
print(c.shape)

(2, 2, 3)


## Special array creation functions

In [15]:
zeros = np.zeros((3,3,4))
print(zeros)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [16]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
full = np.full((2,2),7)
print(full)

[[7 7]
 [7 7]]


In [19]:
ident = np.eye(3)
print(ident)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
arr = np.arange(0,21,4)

print(arr)

[ 0  4  8 12 16 20]


In [26]:
lin = np.linspace(0,10,15)
print(lin)  # equal-inter

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [27]:
random_arr = np.random.rand(2,2) # 0-1
print(random_arr)

[[0.0222772  0.21490389]
 [0.58413352 0.12572207]]


In [29]:
random_z = np.random.randint(1,100,size=5)
print(random_z)

[94 29 16 73 12]


## Array Properties

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [31]:
print(a.shape)  # (2, 3) -> 2 rows, 3 columns

(2, 3)


In [32]:
print(a.size)    # 6 -> total number of elements

6


In [33]:
print(a.ndim)    # 2 -> number of dimensions (2D)

2


In [34]:
print(a.dtype)   # int64 (or int32 on some systems) -> data type of elements

int64


In [35]:
a = np.array([1, 2, 3])
print(a.dtype)  # int64

b = np.array([1.0, 2.0, 3.0])
print(b.dtype)  # float64

c = np.array([1, 2, 3], dtype='float32')
print(c.dtype)  # float32 - explicitly set type

int64
float64
float32


In [36]:
d = np.array([1, 2, 3.5])
print(d)        # [1.  2.  3.5] - all became floats!
print(d.dtype)  # float64

[1.  2.  3.5]
float64


## index - slicing

In [37]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])      # 10  -> first element
print(arr[-1])     # 50  -> last element
print(arr[-2])     # 40  -> second-to-last

print(arr[1:4])    # [20 30 40] -> index 1,2,3 (4 excluded)
print(arr[:3])     # [10 20 30] -> from start to index 2
print(arr[2:])     # [30 40 50] -> from index 2 to end
print(arr[::-1])   # [50 40 30 20 10] -> reversed
print(arr[::2])    # [10 30 50] -> every 2nd element

10
50
40
[20 30 40]
[10 20 30]
[30 40 50]
[50 40 30 20 10]
[10 30 50]


In [38]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [46]:
# matrix[ROW, COLUMN]
# matrix[:, 0]  -> all rows, only column 0
# matrix[0, :]  -> only row 0, all columns

In [47]:
print(matrix[1, 2])     # 6  -> row index 1, column index 2
print(matrix[0])        # [1 2 3] -> entire first row
print(matrix[:, 0])     # [1 4 7] -> entire first column
print(matrix[0:2, 1:3]) # rows 0-1, columns 1-2

6
[1 2 3]
[1 4 7]
[[2 3]
 [5 6]]


In [39]:
matrix.ndim

2

In [40]:
matrix[0]

array([1, 2, 3])

In [42]:
matrix[0][2]

np.int64(3)

In [45]:
matrix[:,0]

array([1, 4, 7])

In [49]:
arr = np.array([10, 20, 30, 40, 50])

mask = arr > 25
print(mask)

[False False  True  True  True]


In [53]:
print(arr[mask])

[30 40 50]


In [54]:
print(arr[arr>25])

[30 40 50]


## Array Operations (Vectorization)

In [55]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [56]:
print(a + b)   # [5 7 9]   - addition
print(a - b)   # [-3 -3 -3] - subtraction
print(a * b)   # [4 10 18]  - multiplication (element-wise, NOT matrix mult)
print(a / b)   # [0.25 0.4 0.5] - division
print(a ** 2)  # [1 4 9]    - power

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [57]:
print(a**b)

[  1  32 729]


In [58]:
a = np.array([1, 2, 3])

print(a + 10)   # [11 12 13] -> 10 added to EVERY element
print(a * 2)    # [2 4 6]
print(a > 1)    # [False True True] -> comparison returns boolean array

[11 12 13]
[2 4 6]
[False  True  True]


In [59]:
# comparing speed

import time

size = 1000000
list1 = list(range(size))
arr1 = np.arange(size)

# List approach
start = time.time()
result = [x * 2 for x in list1]
print("List time:", time.time() - start)

# NumPy approach
start = time.time()
result = arr1 * 2
print("NumPy time:", time.time() - start)

List time: 0.0643606185913086
NumPy time: 0.036580562591552734


## Useful Statistical & Math Functions

In [62]:
arr = np.array([3,4,1,2,5])

print(np.sum(arr))     # 15   -> total
print(np.mean(arr))    # 3.0  -> average
print(np.median(arr))  # 3.0  -> middle value
print(np.max(arr))     # 5
print(np.min(arr))     # 1
print(np.std(arr))     # 1.414... -> standard deviation
print(np.var(arr))     # 2.0  -> variance

15
3.0
3.0
5
1
1.4142135623730951
2.0


In [63]:
print(np.sort(arr))           # sorted array
print(np.argmax(arr))         # 4 -> INDEX of max value
print(np.argmin(arr))         # 0 -> INDEX of min value

[1 2 3 4 5]
4
2


In [65]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])

print(np.sum(matrix))            # 21 -> sum of ALL elements
print(np.sum(matrix, axis=0))    # [5 7 9] -> sum DOWN each column
print(np.sum(matrix, axis=1))    # [6 15]  -> sum ACROSS each row

21
[5 7 9]
[ 6 15]


## reshape

In [69]:
arr = np.array([1,2,3,4,5,6])

print(arr)

reshape1 = arr.reshape(2,3)
print(reshape1)


reshape2 = arr.reshape(3,2)
print(reshape2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [70]:
flat = reshape2.flatten()   # back to 1D
print(flat)  # [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [71]:
!pip install pandas

In [72]:
import pandas as pd

In [74]:
s = pd.Series([10,20,30,40,50,60])
print(s)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64


In [76]:
s2 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s2)

print("-----------------")
print(s2['b'])

a    10
b    20
c    30
dtype: int64
-----------------
20


In [77]:
data = {'math': 90, 'science': 85, 'english': 78}

s3 = pd.Series(data)
print(s3)
# math       90
# science    85
# english    78

math       90
science    85
english    78
dtype: int64


In [78]:
s = pd.Series([10, 20, 30, 40])

print(s.sum())     # 100
print(s.mean())    # 25.0
print(s.max())     # 40
print(s * 2)       # multiplies every element by 2
print(s[s > 15])   # filters - same boolean indexing as NumPy!

100
25.0
40
0    20
1    40
2    60
3    80
dtype: int64
1    20
2    30
3    40
dtype: int64


## DataFrame

In [81]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['NY', 'LA', 'Chicago', 'NY'],
    'Salary': [50000, 60000, 75000, 65000]
}


df = pd.DataFrame(data)
print(df)

      Name  Age     City  Salary
0    Alice   25       NY   50000
1      Bob   30       LA   60000
2  Charlie   35  Chicago   75000
3    David   28       NY   65000


In [82]:
data2 = [
    ['Alice', 25, 'NY'],
    ['Bob', 30, 'LA']
]


df2 = pd.DataFrame(data2, columns=['Name', 'Age', 'City'])
print(df2)

    Name  Age City
0  Alice   25   NY
1    Bob   30   LA


## Reading & Writing Files

In [83]:
df = pd.read_csv("/content/Titanic-Dataset-selected-columns.csv")

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [85]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['NY', 'LA', 'Chicago', 'NY'],
    'Salary': [50000, 60000, 75000, 65000]
}


df = pd.DataFrame(data)
df.to_csv('output.csv', index=False)

In [86]:
# CSV
df = pd.read_csv('data.csv')
df.to_csv('output.csv', index=False)  # index=False avoids writing row numbers

# Excel (requires: pip install openpyxl)
df = pd.read_excel('data.xlsx', sheet_name='Sheet1')
df.to_excel('output.xlsx', index=False)

# JSON
df = pd.read_json('data.json')
df.to_json('output.json')

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [93]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David','Ravi'],
    'Age': [25, 30, 35, 28,32],
    'City': ['NY', 'LA', 'Chicago', 'NY','LN'],
    'Salary': [50000, 60000, 75000, 65000,48000]
}


df = pd.DataFrame(data)
df

,Name,Age,City,Salary
0,Alice,25,NY,50000
1,Bob,30,LA,60000
2,Charlie,35,Chicago,75000
3,David,28,NY,65000
4,Ravi,32,LN,48000


## Exploring Data

In [94]:
df.head()

,Name,Age,City,Salary
0,Alice,25,NY,50000
1,Bob,30,LA,60000
2,Charlie,35,Chicago,75000
3,David,28,NY,65000
4,Ravi,32,LN,48000


In [95]:
df.head(2)

,Name,Age,City,Salary
0,Alice,25,NY,50000
1,Bob,30,LA,60000


In [96]:
df.tail(2)

,Name,Age,City,Salary
3,David,28,NY,65000
4,Ravi,32,LN,48000


In [97]:
print(df.shape)        # (rows, columns) -> e.g. (5, 4)
print(df.columns)      # Index(['Name','Age','City','Salary'])
print(df.index)        # row labels

(5, 4)
Index(['Name', 'Age', 'City', 'Salary'], dtype='object')
RangeIndex(start=0, stop=5, step=1)


In [99]:
print(df.dtypes)       # data type of each column
print("-------------------------------")
print(df.info())       # summary: columns, types, non-null counts, memory

Name      object
Age        int64
City      object
Salary     int64
dtype: object
-------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   City    5 non-null      object
 3   Salary  5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None


In [100]:
print(df.describe())   # statistical summary for numeric columns

             Age        Salary
count   5.000000      5.000000
mean   30.000000  59600.000000
std     3.807887  11104.053314
min    25.000000  48000.000000
25%    28.000000  50000.000000
50%    30.000000  60000.000000
75%    32.000000  65000.000000
max    35.000000  75000.000000


## Unique values & value counts

In [103]:
print(df['City'].unique())
print(df['City'].nunique())       #  number of unique values
print(df['City'].value_counts())  # count of each value

['NY' 'LA' 'Chicago' 'LN']
4
City
NY         2
LA         1
Chicago    1
LN         1
Name: count, dtype: int64


## Selecting Data

In [105]:
print(df['Name'])              # Series - single column
print(df[['Name', 'Age','Salary']])     # DataFrame - multiple columns (note double brackets!)

0      Alice
1        Bob
2    Charlie
3      David
4       Ravi
Name: Name, dtype: object
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000
3    David   28   65000
4     Ravi   32   48000


In [106]:
# .iloc examples
print(df.iloc[0])        # first row (by position)
print(df.iloc[0:2])      # first two rows
print(df.iloc[0, 1])      # row 0, column 1 -> value at that position
print(df.iloc[:, 0])      # all rows, column 0 (first column)

# .loc examples (using default index, which happens to be 0,1,2,3 here)
print(df.loc[0])           # row labeled 0
print(df.loc[0, 'Name'])   # value in row 0, column 'Name'
print(df.loc[0:2, 'Name']) # NOTE: with loc, the end is INCLUSIVE
print(df.loc[:, ['Name','Age']])  # all rows, specific columns

Name      Alice
Age          25
City         NY
Salary    50000
Name: 0, dtype: object
    Name  Age City  Salary
0  Alice   25   NY   50000
1    Bob   30   LA   60000
25
0      Alice
1        Bob
2    Charlie
3      David
4       Ravi
Name: Name, dtype: object
Name      Alice
Age          25
City         NY
Salary    50000
Name: 0, dtype: object
Alice
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28
4     Ravi   32


In [109]:
df[df['Age'] > 28]

,Name,Age,City,Salary
1,Bob,30,LA,60000
2,Charlie,35,Chicago,75000
4,Ravi,32,LN,48000


In [110]:
# AND - use &
print(df[(df['Age'] > 25) & (df['City'] == 'NY')])

# OR - use |
print(df[(df['City'] == 'NY') | (df['City'] == 'LA')])

# NOT - use ~
print(df[~(df['City'] == 'NY')])

    Name  Age City  Salary
3  David   28   NY   65000
    Name  Age City  Salary
0  Alice   25   NY   50000
1    Bob   30   LA   60000
3  David   28   NY   65000
      Name  Age     City  Salary
1      Bob   30       LA   60000
2  Charlie   35  Chicago   75000
4     Ravi   32       LN   48000
